# Generated by Django 5.1.7 on 2025-03-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogi', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
